baseapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("manager/", include("superadmin.urls")),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="home-page"),
    path("company/", views.company, name="company-page"),
    path("mission/", views.mission, name="mission-page"),
    path("people/", views.people, name="people-page"),
    path("solutions/", views.solution_vi, name="solution-page"),
    path("packages-and-courier/", views.packages_courier, name="package-courier-page"),
    path("less-than-truckload/", views.truckload, name="truckload-page"),
    path("logistics/", views.logistic, name="logistic-page"),
    path("investors/", views.investors_page, name="investors-page"),
    path("presentations-and-reports/", views.presentations, name="presentations-page"),
    path("shareholder-information/", views.shareholder, name="shareholder-page"),
    path("contact/", views.contact, name="contact-page"),
    path("terms-of-use/", views.terms, name="terms-page"),
    path("track/", views.track_view, name="track-page"),
]

superadmin/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.dashboard, name="admindashboard"),
    path("sign-out/", views.sign_out, name="sign_out"),
    path("packages/", views.packages_list, name="packages_list"),
    path("packages/<int:pk>/", views.packages_detail, name="packages_detail"),
    path("new-package/", views.new_packages, name="new_package"),
    path("send-mail/", views.send_message, name="send_message"),
]

superadmin/models.py
from django.db import models

# Create your models here.

superadmin/forms.py
from django import forms
from home.models import Package

from baseapp import utils


class NewPackageForm(forms.ModelForm):
    sname = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Shippers Name",
            }
        ),
        label="Shippers Name",
        required=True,
    )

    scountry = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Shipper Country",
            }
        ),
        label="Shippers Country",
        required=True,
    )
    sphone = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Shipper Phone",
            }
        ),
        label="Shippers Phone",
        required=True,
    )

    rphone = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Receiver Phone",
            }
        ),
        label="Receiver Phone",
        required=True,
    )

    rname = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Receiver Name",
            }
        ),
        label="Receiver Name",
        required=True,
    )
    raddress = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Receiver Address",
            }
        ),
        label="Receiver Address",
        required=True,
    )
    rpostal = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Receiver Postal",
            }
        ),
        label="Receiver Postal",
        required=True,
    )
    remail = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Receiver Email",
            }
        ),
        label="Receiver Email",
        required=True,
    )

    track_id = forms.CharField(
        max_length=8,
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "readonly": True,
                "class": "form-control",
            }
        ),
        label="Copy the Track Id",
        required=True,
    )
    origin = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Origin",
            }
        ),
        label="Origin",
        required=True,
    )

    destination = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Destination",
            }
        ),
        label="Destination",
        required=True,
    )

    weight = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "weight",
            }
        ),
        label="weight",
        required=True,
    )

    shipment_mode = forms.CharField(
        widget=forms.Select(
            choices=utils.SHIPMENT_MODE,
            attrs={
                "class": "form-control",
            },
        ),
        label="Shipment Mode",
        required=True,
    )

    carrier_ref_no = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Carrier Ref No",
            }
        ),
        label="Carrier Ref No",
        required=True,
    )

    product = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Product",
            }
        ),
        label="Product",
        required=True,
    )

    quantity = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "number",
                "class": "form-control",
                "placeholder": "Quantity",
            }
        ),
        label="Quantity",
        required=True,
    )

    payment_mode = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Payment Mode",
            }
        ),
        label="Payment Mode",
        required=True,
    )

    departure_date = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Departure Date",
            }
        ),
        label="Departure Date",
        required=True,
    )

    expected_delivery_date = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Expected Delivery Date",
            }
        ),
        label="Expected Delivery Date",
        required=True,
    )

    status = forms.CharField(
        widget=forms.Select(
            choices=utils.STATUS,
            attrs={
                "class": "form-control",
            },
        ),
        label="Status",
        required=True,
    )

    pick_up_date = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Pick up Date",
            }
        ),
        label="Pick up Date",
        required=True,
    )

    current_location = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control",
                "placeholder": "Current Location",
            }
        ),
        label="Current Location",
        required=True,
    )

    class Meta:
        model = Package
        fields = [
            "sname",
            "scountry",
            "sphone",
            "rname",
            "rphone",
            "raddress",
            "rpostal",
            "remail",
            "origin",
            "destination",
            "product",
            "weight",
            "quantity",
            "shipment_mode",
            "carrier_ref_no",
            "payment_mode",
            "departure_date",
            "expected_delivery_date",
            "pick_up_date",
            "current_location",
            "status",
            "track_id",
        ]

superadmin/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from django.contrib import messages

from home.models import Package
from .forms import NewPackageForm
from baseapp import utils
from .decorator import manager_required

from django.core.mail import EmailMessage
from django.template.loader import get_template


def sign_out(request):
    logout(request)
    return redirect("admindashboard")


@manager_required
def dashboard(request):
    context = {
        "packages": Package.objects.all().count(),
        "pending_dev": Package.objects.filter(status=utils.PD).count(),
        "completed_dev": Package.objects.filter(status=utils.DV).count(),
    }
    return render(request, "superadmin/dashboard.html", context)


@manager_required
def packages_list(request):
    packages = Package.objects.all()
    return render(request, "superadmin/packages.html", {"packages": packages})


@manager_required
def packages_detail(request, pk):
    package = get_object_or_404(Package, pk=pk)
    return render(request, "superadmin/package_details.html", {"package": package})


@manager_required
def new_packages(request):
    if request.POST:
        n_form = NewPackageForm(request.POST)

        if n_form.is_valid():
            instance = n_form.save()
            messages.info(request, "Package created")
            return redirect("packages_detail", pk=instance.pk)

    else:
        n_form = NewPackageForm(initial={"track_id": utils.gen_random_ids()})

    return render(
        request,
        "superadmin/newpackage.html",
        {"n_form": n_form},
    )


@manager_required
def send_message(request):
    if request.POST:
        title = request.POST.get("title")
        rname = request.POST.get("rname")
        email = request.POST.get("remail")
        rmessage = request.POST.get("rmessage")

        context = {
            "name": rname,
            "body": rmessage,
        }
        message = get_template("superadmin/mail_temp.html").render(context)
        mail = EmailMessage(
            subject=title,
            body=message,
            from_email=utils.EMAIL_ADMIN,
            to=[email],
            reply_to=[utils.EMAIL_ADMIN],
        )
        mail.content_subtype = "html"
        mail.send(fail_silently=True)

        messages.info(request, "Mail Sent")
        return redirect("send_message")

    return render(request, "superadmin/send_email.html")

templates/superadmin/dashboard.html
{% extends 'layouts/superadmin.html' %}<!---->
{% block title %} Dashboard {% endblock title %}
<!---->
{% block content %}
<!--[container-fluid]-->
<div class="container-fluid" id="container-wrapper">
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
    </ol>
  </div>

  <div class="row mb-3">
    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-4 col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <div class="row align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-uppercase mb-1">
                Total Packages
              </div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">
                {{packages}}
              </div>
              <div class="mt-2 mb-0 text-muted text-xs">
                <span class="text-success mr-2"
                  ><i class="fa fa-arrow-up"></i> 3.48%</span
                >
                <span>Since last month</span>
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-calendar fa-2x text-primary"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Earnings (Annual) Card Example -->
    <div class="col-xl-4 col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-uppercase mb-1">
                Pending delivery
              </div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">
                {{pending_dev}}
              </div>
              <div class="mt-2 mb-0 text-muted text-xs">
                <span class="text-success mr-2"
                  ><i class="fas fa-arrow-up"></i> 12%</span
                >
                <span>Since last years</span>
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-shopping-cart fa-2x text-success"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-4 col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <div class="row align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-uppercase mb-1">
                Completed delivery
              </div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">
                {{completed_dev}}
              </div>
              <div class="mt-2 mb-0 text-muted text-xs">
                <span class="text-success mr-2"
                  ><i class="fa fa-arrow-up"></i> 3.48%</span
                >
                <span>Since last month</span>
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-calendar fa-2x text-primary"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--[container-fluid ends]-->

<!-- Footer -->
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span
        >copyright &copy;
        <script>
          document.write(new Date().getFullYear());
        </script>
        - developed by
        <b><a href="#" target="_blank">Sammy</a></b>
      </span>
    </div>
  </div>
</footer>
<!-- Footer -->
{% endblock content %}

templates/superadmin/mail_temp.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Welcome Email</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
      /**
   * Google webfonts. Recommended to include the .woff version for cross-client compatibility.
   */
      @media screen {
        @font-face {
          font-family: "Source Sans Pro";
          font-style: normal;
          font-weight: 400;
          src: local("Source Sans Pro Regular"), local("SourceSansPro-Regular"),
            url(https://fonts.gstatic.com/s/sourcesanspro/v10/ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03otPbuUS0.woff)
              format("woff");
        }

        @font-face {
          font-family: "Source Sans Pro";
          font-style: normal;
          font-weight: 700;
          src: local("Source Sans Pro Bold"), local("SourceSansPro-Bold"),
            url(https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGFkQc6VGVFSmCnC_l7QZG60.woff)
              format("woff");
        }
      }

      /**
   * Avoid browser level font resizing.
   * 1. Windows Mobile
   * 2. iOS / OSX
   */
      body,
      table,
      td,
      a {
        -ms-text-size-adjust: 100%; /* 1 */
        -webkit-text-size-adjust: 100%; /* 2 */
      }

      /**
   * Remove extra space added to tables and cells in Outlook.
   */
      table,
      td {
        mso-table-rspace: 0pt;
        mso-table-lspace: 0pt;
      }

      /**
   * Better fluid images in Internet Explorer.
   */
      img {
        -ms-interpolation-mode: bicubic;
      }

      /**
   * Remove blue links for iOS devices.
   */
      a[x-apple-data-detectors] {
        font-family: inherit !important;
        font-size: inherit !important;
        font-weight: inherit !important;
        line-height: inherit !important;
        color: inherit !important;
        text-decoration: none !important;
      }

      /**
   * Fix centering issues in Android 4.4.
   */
      div[style*="margin: 16px 0;"] {
        margin: 0 !important;
      }

      body {
        width: 100% !important;
        height: 100% !important;
        padding: 0 !important;
        margin: 0 !important;
      }

      /**
   * Collapse table borders to avoid space between cells.
   */
      table {
        border-collapse: collapse !important;
      }

      a {
        color: black;
      }

      img {
        height: auto;
        line-height: 100%;
        text-decoration: none;
        border: 0;
        outline: none;
      }
    </style>
  </head>
  <body style="background-color: #e9ecef">
    <!-- start preheader -->
    <div
      class="preheader"
      style="
        display: none;
        max-width: 0;
        max-height: 0;
        overflow: hidden;
        font-size: 1px;
        line-height: 1px;
        color: #fff;
        opacity: 0;
      "
    >
      welcome to {{domain}}
    </div>
    <!-- end preheader -->

    <!-- start body -->
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
      <!-- start logo -->
      <tr>
        <td align="center" bgcolor="#e9ecef">
          <!--[if (gte mso 9)|(IE)]>
        <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">
        <tr>
        <td align="center" valign="top" width="600">
        <![endif]-->
          <table
            border="0"
            cellpadding="0"
            cellspacing="0"
            width="100%"
            style="max-width: 600px"
          >
            <tr>
              <td align="center" valign="top" style="padding: 36px 24px">
                <a
                  href="{{domain}}"
                  target="_blank"
                  rel="noopener noreferrer"
                  style="display: inline-block"
                >
                  <img
                    src="https://bluestreamexpress.com/assets/images/bs.png"
                    alt="Logo"
                    border="0"
                    width="150"
                    style="display: block; width: 150px"
                  />
                </a>
              </td>
            </tr>
          </table>
          <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->
        </td>
      </tr>
      <!-- end logo -->

      <!-- start hero -->
      <tr>
        <td align="center" bgcolor="#e9ecef">
          <!--[if (gte mso 9)|(IE)]>
        <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">
        <tr>
        <td align="center" valign="top" width="600">
        <![endif]-->
          <table
            border="0"
            cellpadding="0"
            cellspacing="0"
            width="100%"
            style="max-width: 600px"
          >
            <tr>
              <!--td bgcolor="#ffffff" align="left">
              <img src="#" alt="Welcome" width="600" style="display: block; width: 100%; max-width: 100%;">
            </td--->
            </tr>
          </table>
          <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->
        </td>
      </tr>
      <!-- end hero -->

      <!-- start copy block -->
      <tr>
        <td align="center" bgcolor="#e9ecef">
          <!--[if (gte mso 9)|(IE)]>
        <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">
        <tr>
        <td align="center" valign="top" width="600">
        <![endif]-->
          <table
            border="0"
            cellpadding="0"
            cellspacing="0"
            width="100%"
            style="max-width: 600px"
          >
            <!-- start copy -->
            <tr>
              <td
                bgcolor="#ffffff"
                align="left"
                style="
                  padding: 24px;
                  font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif;
                  font-size: 16px;
                  line-height: 24px;
                "
              >
                <h1
                  style="
                    margin: 0 0 12px;
                    font-size: 20px;
                    font-weight: 400;
                    line-height: 48px;
                  "
                >
                  Dear {{name}}
                </h1>
                <p style="margin: 0">{{body}}</p>
              </td>
            </tr>
            <!-- end copy -->

            <!-- start copy -->
            <tr>
              <td
                align="left"
                bgcolor="#ffffff"
                style="
                  padding: 24px;
                  font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif;
                  font-size: 16px;
                  line-height: 24px;
                  border-bottom: 3px solid #d4dadf;
                "
              >
                <p style="margin: 0">
                  Best Regards,<br />
                  {{domain}}
                </p>
              </td>
            </tr>
            <!-- end copy -->
          </table>
          <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->
        </td>
      </tr>
      <!-- end copy block -->
    </table>
    <!-- end body -->
  </body>
</html>

templates/superadmin/newpackage.html
{% extends "layouts/superadmin.html" %}{% load crispy_forms_tags %}
<!---->
{% block title %} New packages {% endblock title %}<!---->
{% block style %}
<style>
  ul {
    padding: 0;
  }

  ul.user_balance_details li {
    display: inline-block;
    justify-content: space-between;
    padding: 10px;
    border-bottom: 1px solid #f1f4f8;
    text-align: center;
    margin-left: 6px;
  }
</style>
{% endblock style %} {% block content %}
<!--[container-fluid]-->
<div class="container-fluid" id="container-wrapper">
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Packages</h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Packages</li>
    </ol>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="card mb-4">
        <div
          class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
        >
          <h6 class="m-0 font-weight-bold text-primary">Create new package</h6>
        </div>
        <div class="card-body">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}{{ n_form|crispy }}

            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!--[container-fluid ends]-->

<!-- Footer -->
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span
        >copyright &copy;
        <script>
          document.write(new Date().getFullYear());
        </script>
        - developed by
        <b><a href="#" target="_blank">Sammy</a></b>
      </span>
    </div>
  </div>
</footer>
<!-- Footer -->

{% endblock content %} {% block script %}
<script type="text/javascript">
  $("#id_departure_date").datepicker({
    startView: 2,
    format: "yyyy/mm/dd",
    autoclose: true,
    todayHighlight: true,
    todayBtn: "linked",
  });
  $("#id_expected_delivery_date").datepicker({
    startView: 2,
    format: "yyyy/mm/dd",
    autoclose: true,
    todayHighlight: true,
    todayBtn: "linked",
  });
  $("#id_pick_up_date").datepicker({
    startView: 2,
    format: "yyyy/mm/dd",
    autoclose: true,
    todayHighlight: true,
    todayBtn: "linked",
  });
</script>
<script>
  $(document).ready(function () {
    $("#dataTable").DataTable(); // ID From dataTable
    $("#dataTableHover").DataTable(); // ID From dataTable with Hover
  });
</script>
{% endblock script %}

templates/superadmin/packages.html
{% extends 'layouts/superadmin.html' %}
<!---->
{% load crispy_forms_tags %}
<!---->
{% block title %} packages {% endblock title %}
<!---->
{% block style %}
<style></style>
{% endblock style %} {% block content %}

<!--[container-fluid]-->
<div class="container-fluid" id="container-wrapper">
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Packages</h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">packages</li>
    </ol>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="card mb-4">
        <div
          class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
        >
          <h6 class="m-0 font-weight-bold text-primary">DataTables</h6>
        </div>
        <div class="table-responsive p-3">
          <table class="table align-items-center table-flush" id="dataTable">
            <thead class="thead-light">
              <tr>
                <th>Track ID</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
            </thead>

            <tbody>
              {% for obj in packages %}
              <tr>
                <td>
                  <a href="#">{{obj.track_id}}</a>
                </td>

                <td>
                  <a
                    href="#"
                    class="{% if obj.status == 'PENDING' %} text-warning {% else %} text-success {% endif %}"
                    >{{obj.status}}</a
                  >
                </td>

                <td>
                  <a href="{% url 'packages_detail' pk=obj.id %}">Details</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<!--[container-fluid ends]-->

<!-- Footer -->
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span
        >copyright &copy;
        <script>
          document.write(new Date().getFullYear());
        </script>
        - developed by
        <b><a href="#" target="_blank">Sammy</a></b>
      </span>
    </div>
  </div>
</footer>
<!-- Footer -->

{% endblock content %} {% block script %}
<script>
  $(document).ready(function () {
    $("#dataTable").DataTable(); // ID From dataTable
  });
</script>
{% endblock script %}

templates/superadmin/send_email.html
{% extends "layouts/superadmin.html" %}{% load crispy_forms_tags %}
<!---->
{% block title %} Send Message{% endblock title %}<!---->
{% block style %}
<style>
  ul {
    padding: 0;
  }

  ul.user_balance_details li {
    display: inline-block;
    justify-content: space-between;
    padding: 10px;
    border-bottom: 1px solid #f1f4f8;
    text-align: center;
    margin-left: 6px;
  }
</style>
{% endblock style %} {% block content %}
<!--[container-fluid]-->
<div class="container-fluid" id="container-wrapper">
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Packages</h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Message</li>
    </ol>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="card mb-4">
        <div
          class="card-header py-3 d-flex flex-row align-items-center justify-content-between"
        >
          <h6 class="m-0 font-weight-bold text-primary">Send Mail</h6>
        </div>
        <div class="card-body">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group">
              <label for="title">Title </label>
              <input
                type="text"
                class="form-control"
                id="title"
                name="title"
                required
              />
            </div>
            <div class="form-group">
              <label for="name">Receiver Name</label>
              <input
                type="text"
                class="form-control"
                id="name"
                name="rname"
                required
              />
            </div>
            <div class="form-group">
              <label for="remail">Receiver Email</label>
              <input
                type="email"
                class="form-control"
                id="remail"
                name="remail"
                required
              />
            </div>

            <div class="form-group">
              <label for="rmessage">Message</label>
              <textarea
                style="height: 132px"
                class="form-control"
                id="rmessage"
                name="rmessage"
                rows="3"
                required
              ></textarea>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!--[container-fluid ends]-->

<!-- Footer -->
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span
        >copyright &copy;
        <script>
          document.write(new Date().getFullYear());
        </script>
        - developed by
        <b><a href="#" target="_blank">Sammy</a></b>
      </span>
    </div>
  </div>
</footer>
<!-- Footer -->

{% endblock content %} {% block script %} {% endblock script %}